### PR TITLE
Simple refactor

### PR DESCRIPTION
**Pull request by victorporof**
This crate was getting pretty hard to follow.

This splits lib.rs into multiple files. No other changes were made.

Depends on https://github.com/bschwind/yoga-rs/pull/28

### CODE REVIEW

**Comment by victorporof** [comment]
Rebased.

**Comment by victorporof** [comment]
Rebased again.

**Comment by victorporof** [comment]
Only f20b80e and 912a89e are relevant.

**Comment by bschwind** [comment]
Thanks again!

**Pull request merged**
