### PR TITLE
Enable Eq, PartialEq and Hash operations on FlexStyle

### PR DESCRIPTION
**Pull request by victorporof**
Needed for https://github.com/victorporof/rsx-dom

### CODE REVIEW

**Comment by victorporof** [comment]
Needed for https://github.com/victorporof/rsx-dom

**Comment by bschwind** [comment]
Hey, thanks for the PR! I haven't used ordered-float before but I'm familiar with the need for it. Is it a zero-cost abstraction?

**Comment by bschwind** [comment]
(and sorry this isn't on crates.io yet, still working on porting all the tests over and making sure I'm not missing anything)

**Comment by victorporof** [comment]
@bschwind Hey, no worries about crates.io. This is a fantastic library, I was really glad I've found it. You've saved me a great deal of time :)

This should be zero cost, as the OrderedFloat struct is just a wrapper around a type T. Eq, PartialEq and Hash derives are possible on the wrapper type, but using the underlying T should be free.

**Comment by bschwind** [comment]
That's great! I'm not near a computer at the moment but give me a bit to review it later and then we can get it merged.

**Comment by bschwind** [comment]
Everything looks good, merging! Thanks again for the PR.

**Comment by bschwind** [comment]
@victorporof I probably should have asked this before merging, but is there a convenient way to declare styles with floats without having to write `OrderedFloat(1.0)` ? I might need to investigate baking that into a macro or something, being able to tersely describe styles is pretty important to this library.

**Pull request merged**
