### PR TITLE
Test Porting

### PR DESCRIPTION
**Pull request by bschwind**
All tests from [this tree](https://github.com/facebook/yoga/tree/a20bde8444474e7a34352a78073de23c26e08fc5/tests) are being ported here.

### CODE REVIEW

**Comment by victorporof** [comment]
Is this expected to land soon or do you need any help?

**Comment by bschwind** [comment]
It's pretty much just me working on it so I don't have a particular timeframe. I'd say I'm over the halfway point but some of the more exotic tests may slow things down a bit. The regular layout tests are pretty mechanical to port.

I suppose I could consider merging what I have now to master and finish up the rest in another branch if you need something quicker. I believe you're the only user of this crate right this moment :p

**Comment by victorporof** [comment]
It does look like most types I'd be interested in have been added. Having this branch merged to master would definitely help me out, but if you feel like this is way too WIP for now then feel free to carry on.

**Comment by victorporof** [comment]
I can also look into helping you out with porting if you let me know what your process is and what's done so far.

**Comment by bschwind** [comment]
That would be fantastic! I'm essentially just starting at the top from [here](https://github.com/facebook/yoga/tree/a20bde8444474e7a34352a78073de23c26e08fc5/tests) and working my way down.

I realized after the fact that Yoga has a [test generator](https://github.com/facebook/yoga/blob/a20bde8444474e7a34352a78073de23c26e08fc5/gentest/gentest-java.js) but I figured I would get more familiar with all of Yoga's features by porting them manually.

I've built up enough tests that most new ones are copy-paste jobs. My process when starting on a new test file is to copy all the test names and create Rust test stubs. For example, with [YGAlignSelfTest](https://github.com/facebook/yoga/blob/a20bde8444474e7a34352a78073de23c26e08fc5/tests/YGAlignSelfTest.cpp), I'll copy all test names and convert them like so:

```
TEST(YogaTest, align_self_center) {
TEST(YogaTest, align_self_flex_end) {
TEST(YogaTest, align_self_flex_start) {
TEST(YogaTest, align_self_flex_end_override_flex_start) {
TEST(YogaTest, align_self_baseline) {
```

becomes

```
#[test]
fn test_align_self_center() {
	assert!(false);
}

#[test]
fn test_align_self_flex_end() {
	assert!(false);
}

#[test]
fn test_align_self_flex_start() {
	assert!(false);
}

#[test]
fn test_align_self_flex_end_override_flex_start() {
	assert!(false);
}

#[test]
fn test_align_self_baseline() {
	assert!(false);
}
```

Most of the tests follow the same basic pattern:

* Create a root node
* Add some number of child nodes (typically it's 1-3 children on the root node, sometimes child nodes have child nodes as well)
* Set some styles on the root and children
* Compute the layout with Left-to-Right and assert values
* Compute the layout with Right-to-Left and assert values
* Done!

Nothing fancy at the moment. Occasionally I'll come across a test for a measure function or dirty marking validation but these are less common. For those I just read the original test and replicate it as best I can in Rust. If the Rust wrapper doesn't support the feature being tested, that's when I get to work adding it to `lib.rs` The worst one was the "measure function" feature which I think still needs some safety work around it. Unfortunately Yoga doesn't make it very easy because their callbacks don't allow passing pointers to custom user data.

That's it! Let me know if you have any questions.

**Comment by bschwind** [comment]
The most recent test I completed is `flex_direction_test`, so the next I would work on is `flex_test`. To avoid conflicts it'd probably be best to start from the bottom of that list and work up.

**Comment by bschwind** [comment]
Tests we will implement later:

* YGLoggerTest.cpp
* YGMeasureCacheTest.cpp
* YGMeasureModeTest.cpp
* YGMeasureTest.cpp
* YGMemoryFuncTest.cpp
* YGRelayoutTest.cpp (`dont_cache_computed_flex_basis_between_layouts`)
* YGRoundingMeasureFuncTest.cpp

There are new tests in the `master` tree of Yoga which I will port later when I upgrade the Yoga version.

**Comment by bschwind** [comment]
Everything looks good, let's merge it! 🎉

**Pull request merged**
