### PR TITLE
Update yoga

### PR DESCRIPTION
**Pull request by mamaar**
Hi.
I'm not sure why I spent time doing this. I'm not a Yoga user, nor do I know or use Rust.

This request updates Yoga to the current master, the C++ version. It compiles but there are some failing tests. I looked at the first few fails and some are fixed by defining `available_width` and `available_height` in `calculate_layout`, but I don't feel comfortable changing the tests without knowledge of the underlying system...

### CODE REVIEW

**Comment by bschwind** [comment]
Hey @mamaar, welcome and thanks for the PR! To be honest I can't quite call myself a user of Yoga yet either, though I plan to for a future project.

I hope you were able to take a look at https://github.com/bschwind/yoga-rs/pull/37 before taking on such a large amount of work! At this point that PR is a bit stale, and we had some issues with it building properly on Linux.

I _do_ want to get this project updated to the latest code though as it's been sitting here for too long on an older C version. If there's anything specific you need help with, don't hesitate to ask! When I have a good chunk of time (which seems rare these days) I'll try to sit down and get this all reviewed and merged.

**Comment by mamaar** [comment]
Hey!
No, I didn't really check the issues or PRs before. If there's work done on updating Yoga, feel free to close this PR. The change wasn't really a big deal. I deleted the previous Yoga files, copied the new version into the C directory and updated `build.rs` to reference the new files and use c++. Oh yeah, and updated an enum by adding a new value.

**Comment by bschwind** [comment]
Well there's some work done but like I said, it's a bit outdated now. I just need to take a good amount of time to work through these two PRs and get the changes from both in, because the other PR I linked has some additional changes unrelated to upgrading to the newer codebase.

Out of curiosity, as a non-Rust and non-Yoga user, how did you come across this and decide to make a PR? That's kind of an interesting story

**Comment by mamaar** [comment]
I stumbled across Yoga some time ago, but didn't think any more of it as it solves a quite specific problem and a problem I never had. During the weekend I watched a lightning talk from React Europe, by a game developer presenting how they use React for the menu system in the Battlefield games. They use Yoga as a layout engine. 

Later I watched the ongoing Norway Chess tournament on TV, and with Yoga fresh in my mind I thought It would be an interesting exercise to create a GStreamer plugin to create layouts for various video sources. Rust seems like the best choice for GStreamer plugins these days.

This is yet another project I'll never execute on. But it's fun to play around a little and think about new things...

**Comment by bschwind** [comment]
Ah that's cool! I didn't know battlefield 1 uses yoga for their menu layout. It's a shame though because Battlefield 1 is one of my most hated menus because of the insane input latency 😅 The layout itself is good, but if they're running react in JS then that might explain the latency (along with the number of components): https://github.com/mobxjs/mobx/issues/681#issuecomment-375481599

That's an ambitious project but even on an older version of this yoga crate, and a gstreamer crate, you should be able to get quite far. Rust is a nice language to work with.

**Comment by mamaar** [comment]
Yeah, I know, but I need excuses for not doing anything about my ideas ;)

Maybe I'll use the failing tests this PR introduced as a start for learning Rust in practice. I'm going to want to use is sooner or later anyway

**Comment by mamaar** [comment]
Is there a good reason for passing `Undefined` as width/height to `calculate_layout`? This seems to fail many of the `root_layout.width/height()` calls.

**Comment by bschwind** [comment]
Hmm, it depends on the test. I would check the analogous test in the main yoga repo to see what they do. Most if not all our tests are ported from there.

**Comment by mamaar** [comment]
Hey, @bschwind 
The problem was that `Undefined` was defined as NaN and not following the upstream value that comes with following comment:
```
/** Large positive number signifies that the property(float) is undefined.
 *Earlier we used to have YGundefined as NAN, but the downside of this is that
 *we can't use -ffast-math compiler flag as it assumes all floating-point
 *calculation involve and result into finite numbers. For more information
 *regarding -ffast-math compiler flag in clang, have a look at
 *https://clang.llvm.org/docs/UsersManual.html#cmdoption-ffast-math
 **/
#define YGUndefined 10E20F
```

Are the Rust tests manually translated or do you use some automation? I started a new branch in my fork, to hack together a python script that translates the C++ tests to Rust. Next week I'm going away and unless I there's already automation in the picture, I will look at it again when I'm back.

**Comment by bschwind** [comment]
Hey @mamaar , Good catch on the NaN situation!

As for the Rust tests, they were manually translated, though @victorporof may have used some sort of automation because he wrote his tests way faster than me.

**Comment by bschwind** [comment]
Also one question: Do you know the SHA1 of the commit you used when copying over the C++ source files? I currently have a poor-man's git submodule going on in the [readme](https://github.com/bschwind/yoga-rs#yoga-version)

When I started this project I didn't realize how actively developed Yoga was and didn't think it would be changing very frequently, so I ended up with stuff like that.

**Comment by victorporof** [comment]
Sorry to disappoint but I didn't use any automation for these tests :)

**Comment by bschwind** [comment]
From what I can see, the main blockers are:

* A hacky workaround to get it building on linux (my shameful code)
* Some minor merge conflicts
* An older version of bindgen which we may be able to upgrade now

I'm going to experiment a bit with newer versions of bindgen while picking out various pieces of `build.rs` changes from this PR and #43 

If I report back if I get something working.

**Pull request closed without merging**
