### PR TITLE
Add support for serde

### PR DESCRIPTION
**Pull request by victorporof**
Signed-off-by: Victor Porof <victor.porof@gmail.com>

### CODE REVIEW

**Comment by victorporof** [comment]
Opt-in or opt-out? What are your thoughts?

**Comment by bschwind** [comment]
Interesting, what's the use case here? Is this for communicating yoga node data to other languages?

I'm leaning towards opt-in but I'd like to hear more about the motivation behind it.

**Comment by victorporof** [comment]
Precisely! My specific use case is serializing some of these data structures from rust to js as a json string through ffi when compiled to emscripten. A workaround would be to wrap everything in a newtype and custom derive serialization, but that is extremely cumbersome.

**Comment by bschwind** [comment]
Well it looks good to me! It's currently set up for opt-in, correct? If that's the case then I think we can merge this.

**Comment by victorporof** [comment]
Yes

**Comment by bschwind** [comment]
Awesome, merging

**Pull request merged**
