### PR TITLE
Run rustfmt on the entire project dir with default settings

### PR DESCRIPTION
**Pull request by victorporof**
Signed-off-by: Victor Porof <victor.porof@gmail.com>

### CODE REVIEW

**Comment by bschwind** [comment]
Seems reasonable to me. I started a Go project not too long ago and the trailing commas annoyed me at first but I get the reasoning behind it. LGTM!

**Comment by victorporof** [comment]
We can remove the trailing commas if we want to, search for `coma` in https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

**Comment by bschwind** [comment]
I'm guessing the majority of Rust users prefer trailing commas and I'm fine with it as well

**Comment by victorporof** [comment]
I don't think there's any real preference, but I think it's nice to stick to defaults where it make sense.

**Pull request merged**
