### PR TITLE
Fix call to set_context during Node::drop and set should_free=true when orphaning a child node

### PR DESCRIPTION
**Pull request by ennis**
Fix for #39

### CODE REVIEW

**Comment by bschwind** [comment]
Hey @ennis, thanks for the PR, I agree with your conclusions on the issue. Do you happen to have a minimum code snippet that reproduces the issue in #39 ?

Ideally we could add a test so we don't encounter this issue again in the future.

**Comment by ennis** [comment]
Hi! I can reliably reproduce the issue with the following snippet (on windows, without --release):

https://gist.github.com/ennis/2a6e62c862304f3f378cb13880ae7df8

I'm not so sure anymore about the fix, though: it seems that some of the nodes may have an associated "context" object, allocated on the rust side. My proposed fix leaks this object if there's one.
It seems that the problem lies in calling YGNodeFreeRecursive, which prevents any opportunity to reclaim the storage for the context object.

**Comment by ennis** [comment]
I've pushed a fix that removes the use of `YGNodeFreeRecursive` in favor of each `Node` instance managing its own inner_node. `YGNodeFree` properly orphans the children of the node being deleted. The associated context object should be properly deleted if there is one.

**Comment by bschwind** [comment]
Thanks for the update, I'll try to review it soon

**Comment by bschwind** [comment]
I think this looks good, thanks for the fix!

**Pull request merged**
