### PR TITLE
Release/0.4.0

### PR DESCRIPTION
**Pull request by nicoburns**
Now that we've successfully updated yoga, I'm hoping we can get a new version published to crates.io. This PR is to prepare for a release of the newly updated code:

- Upgrades all dependencies to latest versions (no code changes were required)
- Adds `CHANGELOG.md` documenting changes
- Updates version number in `Cargo.toml`. I figured that a minor version bump was warranted here as I think we updated the yoga version by about 4 years.

I wasn't quite sure if I should update the patch versions of dependencies. I think it probably doesn't make a lot of difference as I believe cargo will consider patch versions semver-compatible and choose the patch version it wants to regardless of the patch version we specify.

### CODE REVIEW

**Review by bschwind — APPROVED** [review]
Beautiful!

**Comment by bschwind** [comment]
@nicoburns thanks for the housekeeping on this one, I've published [0.4.0](https://crates.io/crates/yoga), let me know if there's anything else I can help with!

**Comment by nicoburns** [comment]
@bschwind Amazing! I think that's everything for now. I'm probably going to try and periodically update this to the latest yoga, but that should hopefully just be a submodule commit update and a version number bump. I might also partially port Taffy's gentest runner to this library at some point (it's written in Rust, so this would remove the ruby dependency).

**Comment by bschwind** [comment]
> I might also partially port Taffy's gentest runner to this library at some point (it's written in Rust, so this would remove the ruby dependency).

I'd be totally in favor of this! Happy to remove extra language dependencies.

**Pull request merged**
