### PR TITLE
Adding some useful derives

### PR DESCRIPTION
**Pull request by RoyJacobs**
A couple of derives that help with debugging and testing

### CODE REVIEW

**Comment by bschwind** [comment]
Good call! I haven't added too many "quality of life" things to this repo yet. How has the library been so far? I suspect you may have used it more than me at this point!

**Comment by RoyJacobs** [comment]
Haha, it's working as designed for now, and merge requests get accepted quickly :)

I've been working on getting some code together to set up a basic tree of components which in turn gets converted into "Visuals" (which include the Yoga nodes). `FlexStyle` has been quite useful so far, much nicer than having a bunch of setters.

One thing I'm missing is "get" functionality though. It's not urgent, but it would be useful to have when I move beyond the unit test level.

**Comment by bschwind** [comment]
Ah right, I just have public fields on the layout structs at the moment. I'll make an issue for the getters.

**Comment by RoyJacobs** [comment]
I'm not sure, but it could be nice to be able to also retrieve a list of active FlexStyles. I don't think the Yoga API really supports that though, unless you manually loop over all the getters.

**Comment by bschwind** [comment]
Oh like the ones that aren't undefined?

**Comment by RoyJacobs** [comment]
Right. If I put in something like: `vec![Width(100.point()), Height(50.point())]` it would be nice to be able to get that exact list back from a getter.

But this is something I'm *assuming* is nice to have, though. Just regular getters would be very useful as well, to start with.

**Pull request merged**
